// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRaQOtNe-j0_C6IOmi994zT7Yy25TlQQ',
    appId: '1:498702518616:web:7fe9c84a42430a74fe3d2d',
    messagingSenderId: '498702518616',
    projectId: 'movies-videos-app',
    authDomain: 'movies-videos-app.firebaseapp.com',
    storageBucket: 'movies-videos-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk3Ib4MNy4RelUNzeOzey2BEGOMoC58zo',
    appId: '1:498702518616:android:d3bb63b19475bc7efe3d2d',
    messagingSenderId: '498702518616',
    projectId: 'movies-videos-app',
    storageBucket: 'movies-videos-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0qyfKMLn3j4Mniu-E_nZKAIzE6vao6ow',
    appId: '1:498702518616:ios:7231aa68af06f2f2fe3d2d',
    messagingSenderId: '498702518616',
    projectId: 'movies-videos-app',
    storageBucket: 'movies-videos-app.appspot.com',
    iosBundleId: 'com.example.m1TaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0qyfKMLn3j4Mniu-E_nZKAIzE6vao6ow',
    appId: '1:498702518616:ios:a86555a99181851dfe3d2d',
    messagingSenderId: '498702518616',
    projectId: 'movies-videos-app',
    storageBucket: 'movies-videos-app.appspot.com',
    iosBundleId: 'com.example.m1TaskManager.RunnerTests',
  );
}
